# sfbot_moveit_config/config>ros2_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 10  # ros2_control과 동일하게

    joint_trajectory_controller:  # sfbot_arm_controller 대신
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:  # sfbot_arm_controller 대신
  ros__parameters:
    joints:
      - ak70-10-v1_1_continuous
    command_interfaces:
      - position
    state_interfaces:
      - position
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0
      ak70-10-v1_1_continuous:
        trajectory: 0.2
        goal: 0.5
